plugins:
  - jekyll-relative-links
remote_theme: pages-themes/cayman@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - grpc/grpc.md
  - kubernetes/deploy_spring_boot_application_to_k8s.md