plugins:
  - jekyll-relative-links
remote_theme: pages-themes/cayman@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: Learning
description: Một trang Github nhỏ tổng hợp những thứ mình đã tìm hiểu và nghĩ rằng sẽ hữu ích trong quá trình làm việc